import {PIANO_SEQUENCE} from '../data/piano';
import {playSound} from '../systems/audioSystem';
import {useEffect,useRef,useState} from 'react';
import RetroIcon from './RetroIcon';
import SchoolDocument from './SchoolDocument';
import {archivedConversation} from '../systems/messengerSystem';
import {SCHOOL_FILES,CHATS,GALLERY,PIANO} from '../data/continuation';
import {startMemory,matchMemory,readChat} from '../systems/continuationSystem';
import {enqueueThought} from '../systems/thoughtSystem';
export function Score(){return <figure className="score-sheet real-score" aria-label="Partitura"><svg viewBox="0 0 620 120" role="img" aria-label="Melodia da partitura">{[30,43,56,69,82].map(y=><path key={y} d={'M20 '+y+'H600'} stroke="#65715b" fill="none"/>)}{PIANO.notes.map((n,i)=>{const x=55+i*(510/Math.max(1,PIANO.notes.length-1)),y={G4:69,A4:62.5,B4:56,C5:49.5,D5:43,E5:36.5,G5:23.5}[n];return <g key={i}><ellipse cx={x} cy={y} rx="7" ry="5" fill="#20251b" transform={'rotate(-15 '+x+' '+y+')'}/><path d={'M'+(x+6)+' '+y+'v-30'} stroke="#20251b"/><text x={x} y="112" textAnchor="middle" fontSize="14" fill="#20251b">{n}</text></g>;})}</svg><figcaption>{PIANO.phrases.map((phrase,i)=><div key={i}>Frase {i+1}: {phrase.join(' · ')}</div>)}</figcaption></figure>;}
export function SchoolExplorer({save,update}) {
 const [selected,setSelected]=useState(null),[zoom,setZoom]=useState(100),[pageHeight,setPageHeight]=useState(877),pageRef=useRef(null);
 useEffect(()=>{if(!pageRef.current)return;const page=pageRef.current;const measure=()=>setPageHeight(page.offsetHeight);measure();const observer=new ResizeObserver(measure);observer.observe(page);return()=>observer.disconnect();},[selected]);
 const file=SCHOOL_FILES.find(f=>f.id===selected);
 function finish(){update(s=>{const next={...s,continuation:{...s.continuation,schoolRead:[...new Set([...s.continuation.schoolRead,file.id])]},flags:{...s.flags,...(file.id==='enrollment'?{timeClueSeen:true}:{})}};return file.reaction?enqueueThought(next,{id:'school:'+file.id,text:file.reaction}):next;});}
 return <div className="school-explorer">{file?<div className="pdf-reader"><div className="pdf-toolbar"><button onClick={()=>setSelected(null)}>← Arquivos</button><strong>{file.title}</strong><span>Página 1 / 1</span><label>Zoom<select aria-label="Zoom do documento" value={zoom} onChange={e=>setZoom(Number(e.target.value))}>{[75,100,125,150].map(v=><option key={v} value={v}>{v}%</option>)}</select></label></div><div className="pdf-viewport"><div className="pdf-page-sizer" style={{width:620*zoom/100,height:pageHeight*zoom/100}}><div className="pdf-zoom-content" ref={pageRef} style={{width:620,transform:'scale('+zoom/100+')',transformOrigin:'top left'}}><SchoolDocument file={file}/></div></div></div><footer className="pdf-reading-footer"><span>{save.continuation.schoolRead.includes(file.id)?'Documento consultado':'Arquivo da secretaria escolar'}</span><button disabled={save.continuation.schoolRead.includes(file.id)} onClick={finish}>{save.continuation.schoolRead.includes(file.id)?'Leitura concluída':'Concluir leitura'}</button></footer></div>:<><header className="school-folder-header"><RetroIcon id="files" size={44}/><div><h3>Documentos escolares</h3><p>Secretaria · Renata Pedrosa · 5 arquivos</p></div></header><div className="school-file-list">{SCHOOL_FILES.map(f=><button key={f.id} className="file-row" onClick={()=>{setSelected(f.id);setZoom(100);}} aria-label={f.title}><RetroIcon id="file" size={30}/><span>{f.title}<small>Documento escolar · PDF</small></span><span className="file-read-mark">{save.continuation.schoolRead.includes(f.id)?'✓':'Abrir'}</span></button>)}</div></>}</div>;
}
function MemoryPuzzle({save,update}) {
 const [flipped,setFlipped]=useState([]),timer=useRef(null);
 useEffect(()=>{update(startMemory);return()=>clearTimeout(timer.current);},[update]);
 const m=save.continuation.memory;
 function flip(i){if(!save.flags.timeReturned||flipped.length>=2||m.matched.includes(i)||flipped.includes(i))return;
 const next=[...flipped,i];setFlipped(next);
 if(next.length===2){const good=m.deck[next[0]]===m.deck[next[1]];timer.current=setTimeout(()=>{if(good)update(s=>matchMemory(s,...next));setFlipped([]);},good?350:800);}
 }
 return <div className="identity-puzzle"><h3>Confirme sua identidade</h3><p>Volte para quando havia recomeço.</p>{!save.flags.timeReturned?<><div className="memory-grid locked">{Array.from({length:8},(_,i)=><button key={i} disabled aria-label="Peça bloqueada">?</button>)}</div><p role="status">A verificação não responde.</p><button onClick={()=>update(s=>enqueueThought(s,{id:'captchaBlocked',text:'(Recomeço...Onde que eu vi isso?)'}))}>Examinar verificação</button></>:<><p>Encontre os pares de símbolos.</p><div className="memory-grid">{m.deck.map((v,i)=>{const visible=flipped.includes(i)||m.matched.includes(i);return <button key={i} disabled={m.matched.includes(i)||flipped.length===2} onClick={()=>flip(i)} aria-label={visible?'Peça '+(i+1)+' '+['computador','documentos','mensagens','arquivos'][v]:'Revelar peça '+(i+1)}>{visible?<RetroIcon id={['computer','documents','chat','files'][v]} size={38}/>:'?'}</button>;})}</div><p role="status">{m.matched.length/2} de 4 pares</p></>}</div>;
}
const PROFILES={gerancio:{avatar:'avatarGerancio',status:'Ausente',info:'Família Pedrosa',date:'20/09'},priscila:{avatar:'avatarPriscila',status:'Ausente',info:'Que a luz nos guie.',date:'21/09'},tata:{avatar:'avatarRenata',status:'Desconectada',info:'Renata Pedrosa · Piano e ensaios',date:'22/09'}};
export function Messenger({save,update}) {
 const [tab,setTab]=useState(save.continuation.messengerTab||'chats'),[selected,setSelected]=useState(save.continuation.activeChat||null),log=useRef(null),rootRef=useRef(null),[compact,setCompact]=useState(false);
 useEffect(()=>{if(!rootRef.current)return;const root=rootRef.current,measure=()=>setCompact(root.clientHeight<350);measure();const observer=new ResizeObserver(measure);observer.observe(root);return()=>observer.disconnect();},[save.flags.captchaSolved]);
 const chat=archivedConversation(selected),profile=chat?PROFILES[chat.id]:null,read=!!chat&&save.continuation.chatsRead.includes(chat.id);
 useEffect(()=>{if(log.current)log.current.scrollTop=0;},[selected,tab]);
 useEffect(()=>{if(tab==='chats'&&selected==='tata'&&save.flags.explorerUnlocked&&save.flags.captchaSolved&&save.flags.pianoInspected&&!save.flags.scoreReviewedAfterPiano)update(s=>readChat(s,'tata'));},[tab,selected,save.flags.explorerUnlocked,save.flags.captchaSolved,save.flags.pianoInspected,save.flags.scoreReviewedAfterPiano,update]);
 function select(id){setSelected(id);update(s=>readChat({...s,continuation:{...s.continuation,activeChat:id}},id));}
 function switchTab(value){setTab(value);update(s=>({...s,continuation:{...s.continuation,messengerTab:value}}));}
 if(!save.flags.explorerUnlocked)return <article><h3>Iwakura Messenger</h3><p>A sessão de arquivos ainda está restrita.</p></article>;
 if(!save.flags.captchaSolved)return <MemoryPuzzle save={save} update={update}/>;
 return <div ref={rootRef} className={'story-messenger msn-app'+(compact?' compact':'')}><nav className="msn-toolbar"><span><RetroIcon id="chat" size={22}/> Iwakura Messenger</span><button className={tab==='chats'?'active':''} onClick={()=>switchTab('chats')}>Conversas</button><button className={tab==='gallery'?'active':''} onClick={()=>switchTab('gallery')}>Galeria</button></nav>{tab==='chats'?<div className="msn-layout"><aside className="msn-contacts"><header className="msn-account"><RetroIcon id="avatarMurilo" size={48}/><div><strong>Murilo Pedrosa</strong><small>Conta local · Disponível</small></div></header><div className="msn-group">Contatos (3)</div>{CHATS.map(c=><button aria-label={c.name} className={selected===c.id?'selected':''} key={c.id} onClick={()=>select(c.id)}><RetroIcon id={PROFILES[c.id].avatar} size={34}/><span><strong>{c.name}</strong><small>{PROFILES[c.id].status}</small></span><span className="msn-read">{save.continuation.chatsRead.includes(c.id)?'✓':'○'}</span></button>)}<div className="msn-archive"><RetroIcon id="documents" size={22}/><span>Histórico de mensagens<br/><small>Conversas preservadas nesta conta</small></span></div></aside><section className="msn-conversation">{chat?<><header className="msn-contact-profile"><RetroIcon id={profile.avatar} size={52}/><div><h3>{chat.name}</h3><p>{profile.info}</p><small>{profile.status} · Histórico {profile.date}</small></div></header><div ref={log} className="msn-history" role="log" aria-label={'Histórico com '+chat.name}><div className="msn-date">{profile.date} · Conversa armazenada</div>{chat.lines.map(([speaker,text],i)=><div className={'msn-message '+(speaker==='Murilo'?'sent':'')} key={i}><div><strong>{speaker||'Anexo'}</strong><time>{String(18+Math.floor(i/6)).padStart(2,'0')}:{String(12+i*3%60).padStart(2,'0')}</time></div><p>{text}</p>{!speaker&&<Score/>}</div>)}</div><footer className="msn-status">{read?'✓ Registro consultado · Histórico completo':'Histórico completo · Selecione o contato para registrar a leitura'}</footer></>:<div className="msn-empty"><RetroIcon id="chat" size={48}/><h3>Conversas arquivadas</h3><p>Selecione um contato para consultar o histórico.</p><small>As mensagens desta conta estão preservadas para leitura.</small></div>}</section></div>:<div className="gallery-grid">{GALLERY.map(([text,title],i)=><button key={i} onClick={()=>{if(i===3)playSound('16');update(s=>({...s,continuation:{...s.continuation,gallerySeen:[...new Set([...s.continuation.gallerySeen,String(i)])]},flags:{...s.flags,...(i===3?{scoreDiscovered:true,...(s.flags.pianoInspected?{scoreReviewedAfterPiano:true}:{})}:{})}}));}}><h4>{title}</h4>{i===3?<Score/>:<div className="gallery-placeholder"><RetroIcon id="image" size={48}/></div>}<p>{text}</p>{save.continuation.gallerySeen.includes(String(i))&&'✓'}</button>)}</div>}</div>;
}
