(async()=>{
 window.__smokeStatus='RUNNING';window.__smokeStep='start';
 const delay=ms=>new Promise(r=>setTimeout(r,ms)),assert=(v,msg)=>{if(!v)throw Error(msg);};
 const state=()=>JSON.parse(window.bridge.readSave());
 async function wait(fn,label,timeout=12000){window.__smokeStep=label;for(let n=0;n<timeout/60;n++){if(fn())return;await delay(60);}throw Error('Timeout '+label+' | '+document.body.innerText.slice(-1800));}
 const button=name=>[...document.querySelectorAll('button')].find(b=>(b.getAttribute('aria-label')||b.textContent.trim())===name&&!b.disabled&&b.getClientRects().length&&!b.closest('[inert]'));
 async function click(name){await wait(()=>button(name),'button '+name);button(name).click();await delay(100);}
 async function drain(){for(let i=0;i<30&&document.querySelector('.npc-overlay-box');i++){if(button('Recolher bloco de notas'))return;await click(button('Continuar')?'Continuar':'Voltar');}}
 async function thought(){if(document.querySelector('.os-thought-overlay'))await click('Continuar');}
 async function capture(name){await delay(150);window.__smokeCapture=name;await wait(()=>!window.__smokeCapture,'capture '+name);}
 function input(selector,value){const el=document.querySelector(selector);assert(el,'input '+selector);Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));}
 async function car(id){await wait(()=>document.querySelector('.scene-view')?.dataset.car===id&&!document.querySelector('.travel-fade')&&!document.querySelector('.notebook-overlay'),'car '+id);await drain();}
 async function talk(label){await click(label);await drain();}
 async function notebook(){await click('Usar notebook');await wait(()=>document.querySelector('.login-screen')||document.querySelector('.desktop'),'notebook');}
 async function resize(size){window.__smokeResize=size;await wait(()=>!window.__smokeResize,'resize '+size);await delay(220);}
 async function hands(){await wait(()=>document.querySelector('.hands-vision'),'hands');await delay(850);await capture('hands-'+(state().flags.confrontationComplete?'escape':'bible'));await click('Olhar novamente');await capture('hands-second-'+(state().flags.confrontationComplete?'escape':'bible'));await click(state().flags.confrontationComplete?'Fugir':'Seguir viagem');}
 async function messagesExit(){await click('Afastar-se');await drain();await hands();}
 try{
 await wait(()=>document.querySelector('.main-menu'),'menu');await click('Continuar viagem');
await wait(()=>document.querySelector('.arrival-vision')?.dataset.phase==='hands','arrival hands');await capture('chegada-maos');await wait(()=>document.querySelector('.arrival-vision')?.dataset.phase==='ellipsis','arrival ellipsis');await capture('chegada-reticencias');await wait(()=>document.querySelector('.arrival-vision')?.dataset.phase==='thought','arrival thought');assert(document.body.innerText.includes('Eu não queria isso. Eu nunca quis isso.'),'arrival recognition');await capture('chegada-pensamento');await wait(()=>state().flags.arrivalVisionSeen&&!document.querySelector('.arrival-vision'),'arrival finished');await capture('vagao-final');
 assert(state().currentCarId==='vagao4','final wagon identity');await click('Examinar teclado');await capture('piano-inspecao');await click('Tocar piano');assert(document.querySelectorAll('.piano-art-key').length===15,'15 piano keys');await click('Voltar ao vagão');await click('Voltar ao computador · procurar partitura');await wait(()=>document.querySelector('.story-messenger'),'safe return to computer');assert(state().flags.escapeComplete&&!document.querySelector('.escape-game'),'no repeated chase');await click('Galeria');document.querySelector('.gallery-grid button:last-child').click();await delay(120);await click('Afastar-se');await car('vagao2');await click('Voltar ao Vagão 4');await car('vagao4');assert(!document.querySelector('.arrival-vision'),'arrival does not repeat on return');await click('Examinar teclado');await click('Tocar piano');assert(!document.querySelector('.piano-score')&&!button('Consultar bloco de notas'),'piano has no score overlay');
 for(const size of ['1280x720','1366x768','1920x1080','820x900']){await resize(size);const p=document.querySelector('.piano-artboard').getBoundingClientRect();assert(p.left>=0&&p.top>=0&&p.right<=innerWidth&&p.bottom<=innerHeight,'piano bounds '+size);await capture('piano-'+size);}
 assert([...document.querySelectorAll('.piano-art-key')].every(k=>k.querySelector('.piano-key-label')?.textContent===k.dataset.key),'all keys labeled with score IDs');const neutralFooter=document.querySelector('.piano-compact-footer p').textContent;
 const note=n=>{const b=button('Tocar '+n);b.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:1}));b.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:1}));};
 note('A5');await delay(100);assert(!state().continuation.pianoSolved,'wrong note');assert(document.querySelector('.piano-compact-footer p').textContent===neutralFooter,'no wrong note hint');await click('Recomeçar sequência');
 for(const n of ['A2','A3','A6','A2','A3','A6']){note(n);await delay(200);if(document.querySelector('.piano-compact-footer p'))assert(document.querySelector('.piano-compact-footer p').textContent===neutralFooter,'no partial correctness hint');}
 await wait(()=>document.querySelector('.ending-cinematic'),'cinematic begins');assert(!document.querySelector('.game-cursor')&&!document.querySelector('.world-actions'),'cinematic hides HUD');assert(!button('Continuar'),'no advance during cinema');await wait(()=>document.querySelector('.ending-cinematic')?.dataset.phase==='dialogue','final dialogue after piano',5000);assert(!document.querySelector('.ending-hands'),'hands not repeated after piano');await capture('final-fala-sombra');assert(!button('Continuar'),'automatic dialogue');await wait(()=>document.querySelector('.ending-credits'),'credits summary',45000);for(const size of ['1280x720','1366x768','1920x1080','820x900']){await resize(size);await capture('creditos-'+size);assert(document.querySelector('.ending-credits').getBoundingClientRect().bottom<=innerHeight,'credits fit '+size);}assert(document.body.innerText.includes('Amanda Queiroz')&&document.body.innerText.includes('Victor Monteiro'),'named credits');assert(!button('Continuar'),'wait for full song');await wait(()=>button('Continuar'),'music finishes and Continue appears',110000);const endEvents=JSON.parse(window.bridge.audioEvents());assert(endEvents.filter(e=>e.id==='28'&&e.action==='requested').length===1,'single continuous ending track');assert(endEvents.some(e=>e.id==='28'&&e.action==='ended'),'real track ended');await capture('creditos-continuar');await click('Continuar');await wait(()=>document.querySelector('.main-menu'),'return to menu',5000);assert(state().flags.gameComplete&&state().flags.endingReturnedToMenu,'ending completion saved');await capture('menu-apos-creditos');

 window.__smokeReport='PASS: chegada com mãos, depois reticências e pensamento em tela preta; retorno ao vagão; cena não repete ao voltar do computador; piano inicia diretamente conversa final; créditos e retorno ao menu; quatro resoluções.';window.__smokeStatus='PASS';
 }catch(e){try{await capture('failure-chegada');}catch{}window.__smokeStatus='FAIL '+e.message;}
})();
