(async()=>{
 window.__smokeStatus='RUNNING';window.__smokeStep='start';
 const delay=ms=>new Promise(r=>setTimeout(r,ms)),assert=(v,msg)=>{if(!v)throw Error(msg);};
 const state=()=>JSON.parse(window.bridge.readSave());
 async function wait(fn,label,timeout=12000){window.__smokeStep=label;for(let n=0;n<timeout/60;n++){if(fn())return;await delay(60);}throw Error('Timeout '+label+' | '+document.body.innerText.slice(-1800));}
 const button=name=>[...document.querySelectorAll('button')].find(b=>(b.getAttribute('aria-label')||b.textContent.trim())===name&&!b.disabled&&b.getClientRects().length&&!b.closest('[inert]'));
 async function click(name){await wait(()=>button(name),'button '+name);button(name).click();await delay(100);}
 async function drain(){for(let i=0;i<30&&document.querySelector('.npc-overlay-box');i++){if(button('Recolher bloco de notas'))return;await click(button('Continuar')?'Continuar':'Voltar');}}
 async function thought(){if(document.querySelector('.os-thought-overlay'))await click('Continuar');}
 async function capture(name){await delay(150);window.__smokeCapture=name;await wait(()=>!window.__smokeCapture,'capture '+name);}
 function input(selector,value){const el=document.querySelector(selector);assert(el,'input '+selector);Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));}
 async function car(id){await wait(()=>document.querySelector('.scene-view')?.dataset.car===id&&!document.querySelector('.travel-fade')&&!document.querySelector('.notebook-overlay'),'car '+id);await drain();}
 async function talk(label){await click(label);await drain();}
 async function notebook(){await click('Usar notebook');await wait(()=>document.querySelector('.login-screen')||document.querySelector('.desktop'),'notebook');}
 async function resize(size){window.__smokeResize=size;await wait(()=>!window.__smokeResize,'resize '+size);await delay(220);}
 async function hands(){await wait(()=>document.querySelector('.hands-vision'),'hands');await delay(850);await capture('hands-'+(state().flags.confrontationComplete?'escape':'bible'));await click('Olhar novamente');await capture('hands-second-'+(state().flags.confrontationComplete?'escape':'bible'));await click(state().flags.confrontationComplete?'Fugir':'Seguir viagem');}
 async function messagesExit(){await click('Afastar-se novamente');await drain();await hands();}
 try{
 await wait(()=>document.querySelector('.sound-warning'),'sound warning');await capture('aviso-sonoro');assert(!document.querySelector('.sound-warning button'),'splash automatic without buttons');await wait(()=>document.querySelector('.main-menu'),'automatic menu');
 if(window.__persistenceResume){await click('Continuar viagem');await wait(()=>document.querySelector('.ending-credits'),'restored ending');assert(state().flags.gameComplete,'ending saved');assert(state().continuation.clock.solved&&state().flags.captchaSolved,'puzzles saved');assert(state().continuation.attempts>=1,'retry saved');assert(!document.querySelector('.save-error'),'no save error');await capture('final-reopened');window.__smokeReport='PASS: native save reopened in second executable process; final, clock, memory, retry and journal persisted.';window.__smokeStatus='PASS';return;}
 await click('Novo jogo');if(button('Começar de novo →'))await click('Começar de novo →');await wait(()=>!document.querySelector('.timed-intro')&&document.querySelector('.scene-view'),'timed intro',22000);await drain();
 await talk('Silhueta lendo a Bíblia');assert(!state().flags.bibleSeen,'initial Bible is not clue encounter');
 await click('Ir ao Vagão 2');await car('vagao2');assert(!document.querySelector('.shadow-visible'),'initial window clean');assert(document.querySelector('.clean-window'),'clean curtains layer');await capture('janela-inicial-sem-sombra');await talk('Examinar bloco de notas');await click('Recolher bloco de notas');assert(document.querySelector('.pickup-table-patch'),'notepad removed from table');await capture('mesa-sem-bloco');
 await click('Abrir bloco de notas');await click('Mostrar tudo');assert(document.body.innerText.includes('04/06/2000 - motivação?'),'original note retained');await capture('diario-topo');const rings=document.querySelector('.journal-rings').getBoundingClientRect(),book=document.querySelector('.journal-book').getBoundingClientRect();assert(rings.width>rings.height&&rings.top<book.top+10,'rings on top');
 await click('Fechar bloco de notas');await wait(()=>!document.querySelector('.journal-book'),'journal closes');
 assert(!state().journal.completed.includes('voices'),'conversation objective pending before Bible');await notebook();
 input('[aria-label="Senha do notebook"]','wrong');await click('Entrar');assert(!state().notebookAuthenticated,'wrong login');
 input('[aria-label="Senha do notebook"]','04/06/2000');await click('Entrar');await wait(()=>document.querySelector('.glitch-transition'),'login glitch');assert(state().flags.loginGlitchPending&&state().visualState==='white','login changes color after glitch');await capture('glitch-login');await wait(()=>!document.querySelector('.glitch-transition')&&state().visualState==='black','glitch ended');await thought();
 for(let i=0;i<5;i++){const area=document.querySelector('.script-text');area.scrollTop=area.scrollHeight;area.dispatchEvent(new Event('scroll',{bubbles:true}));await delay(100);await click('Concluir leitura');await thought();if(i<4)await click('Próximo arquivo →');}
 await click('Explorar pasta de arquivos →');await click('Explorador de arquivos · acesso restrito');await thought();
 assert(!state().flags.shadowRevealed&&!document.querySelector('.shadow-visible'),'opening folder does not reveal shadow');input('[aria-label="Senha da pasta"]','77E');await click('Verificar senha');assert(!state().flags.explorerUnlocked,'reject legacy code');await click('OK');
 await click('Afastar-se ESC');await car('vagao2');assert(!state().flags.shadowSeen&&!document.querySelector('.shadow-visible'),'wrong archives password keeps black without shadow');assert(state().visualState==='black','black before correct archives password');
 await click('← Voltar ao Vagão 1');await car('vagao1');await click('Silhueta lendo a Bíblia');await capture('biblia');await drain();await hands();assert(state().flags.handsBibleSeen,'Bible clue before shadow prevents deadlock');assert(state().journal.completed.includes('voices'),'Bible objective');
 await click('Ir ao Vagão 2');await car('vagao2');await notebook();await click('Arquivos');input('[aria-label="Senha da pasta"]','415');await click('Verificar senha');await wait(()=>document.querySelector('.glitch-transition'),'archives glitch');assert(state().visualState==='black','white waits for glitch');/* Timed audio cue: do not force a synchronous WebView snapshot during this 1.5 s interval. */await wait(()=>!document.querySelector('.glitch-transition'),'archives glitch ended');const cueEvents=JSON.parse(window.bridge.audioEvents());const cueTime=id=>cueEvents.find(e=>e.id===id&&e.action==='requested').ms;const cueOffset=Number(cueEvents.find(e=>e.id==='glitch-2-3'&&e.action.startsWith('seek:'))?.action.slice(5)||0);assert(Math.abs(cueTime('25')-cueTime('glitch-2-3')+cueOffset*1000-1500)<150,'archives cue deadline without capture '+JSON.stringify(window.__glitchTiming)+' offset '+cueOffset+' gap '+(cueTime('25')-cueTime('glitch-2-3')));await car('vagao2');assert(state().flags.shadowSeen&&state().visualState==='white','correct password reveals shadow in white');assert(document.querySelector('.shadow-visible'),'shadow visible');await capture('sombra');
 await talk('Examinar sombra e cortina');await wait(()=>document.querySelector('.glitch-transition'),'curtain glitch');await capture('glitch-cortina');await wait(()=>!document.querySelector('.glitch-transition'),'curtain glitch ended');await wait(()=>state().visualState==='black'&&!document.querySelector('.shadow-visible'),'closed curtains black without shadow');await capture('janela-apos-cortina');await notebook();await click('Arquivos');await wait(()=>document.querySelector('.school-explorer'),'school unlocked');
 for(const title of ['Declaração de guardião legal.pdf','Matrícula escolar — Renata Pedrosa.pdf','Horário escolar 9ºA','Horário escolar 9ºB','Advertência Escolar(4).pdf']){await click(title);await click('Concluir leitura');await thought();await capture('documento-'+(title.includes('Matrícula')?'matricula':title.includes('9ºA')?'horarioA':title.includes('9ºB')?'horarioB':title.includes('guardião')?'responsavel':'advertencia'));if(title.includes('Matrícula')){const select=document.querySelector('[aria-label="Zoom do documento"]');select.value='150';select.dispatchEvent(new Event('change',{bubbles:true}));await capture('documento-zoom150');}await click('← Arquivos');}
 await click('Mensagens');await click('Examinar verificação');await thought();assert(document.querySelector('.memory-grid.locked'),'captcha locked');await capture('captcha-bloqueado');
 await click('Afastar-se ESC');await car('vagao2');await click('Ir ao Vagão 3');await car('vagao3');await click('Examinar relógio');assert(!document.querySelector('.clock-controls'),'first click inspection');assert(document.body.innerText.includes('O relógio parece quebrado.'),'clock thought');await capture('relogio-primeira-aproximacao');await click('Voltar ao vagão');await click('Examinar relógio');await click('Manipular relógio');for(const size of ['1280x720','1366x768','1920x1080','820x900']){await resize(size);await capture('relogio-ui-'+size);const panel=document.querySelector('.clock-controls').getBoundingClientRect();assert(panel.left>=0&&panel.right<=innerWidth,'clock panel bounds '+size);}await resize('1280x720');
 input('[aria-label="Horas do relógio"]','0');await delay(100);input('[aria-label="Minutos do relógio"]','13');await click('Confirmar horário');assert(!state().flags.timeReturned,'wrong confirmed time');input('[aria-label="Minutos do relógio"]','14');await delay(100);assert(!state().flags.timeReturned,'time needs confirmation');await capture('relogio-0014-confirmacao');await click('Confirmar horário');await wait(()=>document.querySelector('.clock-resolution'),'clock fade');await delay(800);await capture('relogio-fade');await wait(()=>!document.querySelector('.clock-world'),'return from clock');assert(state().flags.timeReturned,'correct confirmed time');await drain();await click('← Voltar ao Vagão 2');await car('vagao2');await notebook();await click('Mensagens');
 await wait(()=>state().continuation.memory.deck.length===8,'deck ready');
 const deck=state().continuation.memory.deck;for(let v=0;v<4;v++){const pair=deck.map((x,i)=>x===v?i:-1).filter(i=>i>=0);for(const i of pair){const b=document.querySelectorAll('.memory-grid button')[i];b.click();await delay(100);}await delay(450);}
 await wait(()=>state().flags.captchaSolved,'captcha solved');await capture('messenger');assert([...document.querySelectorAll('.msn-contact-profile .os-sprite')].every(c=>c.dataset.ready==='true'),'profile portraits loaded');
 await click('Galeria');for(const b of [...document.querySelectorAll('.gallery-grid button')]){b.click();await delay(100);}await capture('galeria');await click('Conversas');
 for(const name of ['Gerâncio','Priscila','Tata']){await click(name);assert(!button('Próxima mensagem'),'no next-message control');if(name==='Tata'){for(const size of ['1280x720','1366x768','1920x1080','820x900']){await resize(size);await capture('msn-'+size);const compose=document.querySelector('.msn-compose').getBoundingClientRect(),windowRect=document.querySelector('.msn-app').closest('.win-content').getBoundingClientRect();assert(compose.bottom<=windowRect.bottom+2,'compose within OS window '+size);}await resize('1280x720');}for(let i=0;i<12&&button('Enviar');i++)await click('Enviar');if(name!=='Tata')await capture('msn-'+name.toLowerCase());}
 await thought();await drain();await hands();await wait(()=>document.querySelector('.escape-game'),'first chase');await capture('fuga');
 await wait(()=>state().flags.retryPending,'intentional capture');assert(state().flags.captchaSolved,'capture keeps solved captcha');await wait(()=>document.querySelector('.story-messenger'),'checkpoint desktop');await capture('checkpoint-captura');await messagesExit();
 await wait(()=>document.querySelector('.escape-game'),'retry chase');
 await click('Menu');const pausedSnapshot=JSON.stringify(state().chase);await delay(750);assert(JSON.stringify(state().chase)===pausedSnapshot,'pause freezes simulation');await click('Voltar ao menu inicial');await click('Não');await click('Continuar viagem');
 const seen=new Set();let held=new Set();
 function drive(wanted){for(const key of held)if(!wanted.has(key))window.dispatchEvent(new KeyboardEvent('keyup',{key,bubbles:true}));for(const key of wanted)if(!held.has(key))window.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));held=wanted;}
 for(let n=0;n<1600&&document.querySelector('.escape-game');n++){
  const position=document.querySelector('.escape-game canvas')?.dataset.position;const c=position?JSON.parse(position):state().chase;if(c){seen.add(c.wagon);assert(c.phase!=='caught','retry must avoid obstacles');const next=c.hands.filter(h=>h.y<c.y+35).sort((a,b)=>b.y-a.y)[0];const target=next?(next.side==='left'?225:135):180;const wanted=new Set();if(c.x<target-6)wanted.add('ArrowRight');if(c.x>target+6)wanted.add('ArrowLeft');if(Math.abs(c.x-target)<12||!next||c.y-next.y>140)wanted.add('ArrowUp');drive(wanted);}
  await delay(35);
 }
 drive(new Set());assert(seen.size===5,'five wagons '+seen.size);
 await wait(()=>state().flags.escapeComplete,'escape complete');await wait(()=>!document.querySelector('.glitch-transition'),'red glitch ends');assert(state().visualState==='red','red after escape');await capture('vagao-final');
 assert(state().currentCarId==='vagao4','final wagon identity');await click('Examinar teclado');await capture('piano-inspecao');await click('Tocar piano');assert(document.querySelectorAll('.piano-art-key').length===15,'15 piano keys');await click('Voltar ao vagão');await click('Voltar ao computador · procurar partitura');await wait(()=>document.querySelector('.story-messenger'),'safe return to computer');assert(state().flags.escapeComplete&&!document.querySelector('.escape-game'),'no repeated chase');await click('Galeria');document.querySelector('.gallery-grid button:last-child').click();await delay(120);await click('Afastar-se ESC');await car('vagao2');await click('Voltar ao Vagão 4');await car('vagao4');await click('Examinar teclado');await click('Tocar piano');assert(!document.querySelector('.piano-score')&&!button('Consultar bloco de notas'),'piano has no score overlay');
 for(const size of ['1280x720','1366x768','1920x1080','820x900']){await resize(size);const p=document.querySelector('.piano-artboard').getBoundingClientRect();assert(p.left>=0&&p.top>=0&&p.right<=innerWidth&&p.bottom<=innerHeight,'piano bounds '+size);await capture('piano-'+size);}
 const note=n=>{const b=button('Tocar '+n);b.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:1}));b.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:1}));};
 note('A5');await delay(100);assert(!state().continuation.pianoSolved,'wrong note');await click('Recomeçar sequência');
 for(const n of ['A4','A6','A8','A6','A5','A4']){note(n);await delay(200);}
 await wait(()=>document.querySelector('.ending-cinematic'),'cinematic begins');assert(!document.querySelector('.game-cursor')&&!document.querySelector('.world-actions'),'cinematic hides HUD');assert(!button('Continuar'),'no advance during cinema');await wait(()=>document.querySelector('.ending-cinematic')?.dataset.phase==='ellipsis','Murilo ellipsis');await capture('final-reticencias');await wait(()=>document.querySelector('.ending-cinematic')?.dataset.phase==='hands','bloodied hands');await capture('final-maos-sangrentas');assert(document.body.innerText.includes('Eu não queria isso. Eu nunca quis isso.'),'recognition thought');await wait(()=>document.querySelector('.ending-cinematic')?.dataset.phase==='dialogue','automatic final dialogue',15000);await capture('final-fala-sombra');assert(!button('Continuar'),'automatic dialogue');await wait(()=>document.querySelector('.ending-credits'),'credits summary',45000);for(const size of ['1280x720','1366x768','1920x1080','820x900']){await resize(size);await capture('creditos-'+size);assert(document.querySelector('.ending-credits').getBoundingClientRect().bottom<=innerHeight,'credits fit '+size);}assert(document.body.innerText.includes('Amanda Queiroz')&&document.body.innerText.includes('Victor Monteiro'),'named credits');assert(!button('Continuar'),'wait for full song');await wait(()=>button('Continuar'),'music finishes and Continue appears',110000);const endEvents=JSON.parse(window.bridge.audioEvents());assert(endEvents.filter(e=>e.id==='28'&&e.action==='requested').length===1,'single continuous ending track');assert(endEvents.some(e=>e.id==='28'&&e.action==='ended'),'real track ended');await capture('creditos-continuar');await click('Continuar');await wait(()=>document.querySelector('.main-menu'),'return to menu',5000);assert(state().flags.gameComplete&&state().flags.endingReturnedToMenu,'ending completion saved');await capture('menu-apos-creditos');
 const nativeEvents=JSON.parse(window.bridge.audioEvents());assert(!nativeEvents.some(e=>e.action.startsWith('error')),'native audio errors '+JSON.stringify(nativeEvents.filter(e=>e.action.startsWith('error'))));const stamp=id=>nativeEvents.find(e=>e.id===id&&e.action==='requested')?.ms;assert(Math.abs(stamp('22')-stamp('4')-4000)<130,'intro text/audio at 4s');assert(Math.abs(stamp('23')-stamp('4')-9500)<130,'stage 1 at 9.5s actual '+(stamp('23')-stamp('4')));for(const [effect,music,delay] of [['glitch-1-2','24',2500],['glitch-2-3','25',1500],['glitch-3-4','26',4000],['glitch-4-5','27',500]]){const seek=nativeEvents.find(e=>e.id===effect&&e.action.startsWith('seek:'));const offset=seek?Number(seek.action.slice(5)):0;assert(Math.abs(stamp(music)-stamp(effect)+offset*1000-delay)<150,'glitch/music time '+effect+' measured '+(stamp(music)-stamp(effect))+' offset '+offset);}assert(['6','4','22','23','24','25','26','27','31','note-A4'].every(id=>nativeEvents.some(e=>e.id===id&&e.action==='requested')),'native audio event coverage');window.__smokeReport='PASS: real audio, automatic splash/intro, timed glitches, picked-up notebook, original clue, Pedrosa, 15-key art piano and safe computer return; full route from new game through Bible/415, five school documents, clock 00:14, blocked/unblocked memory, gallery and 3 chats, forced exit, real capture/retry, exactly 5 top-down escape wagons, red return, real piano artwork / technical melody, canonical ending; sound warning, cinematic hands, PDF-style school documents and zoom, two-stage clock confirmation/blackout, scripted MSN sends with accumulated history, journal reconciliation; four clock/MSN/piano resolutions; native persistence; continuous 137-second cinematic, bloodied hands, automatic final dialogue, named credits and delayed return to menu.';
 window.__smokeStatus='PASS';
 }catch(e){try{await capture('failure');}catch{}window.__smokeStatus='FAIL '+e.message;}
})();




