(async()=>{
 window.__smokeStatus='RUNNING';window.__smokeStep='evidence review';const delay=ms=>new Promise(r=>setTimeout(r,ms)),assert=(v,m)=>{if(!v)throw Error(m);};
 async function wait(fn,label){window.__smokeStep=label;for(let t=0;t<16000;t+=70){if(fn())return;await delay(70);}throw Error('Timeout '+label);}
 async function capture(name){await delay(350);window.__smokeCapture=name;await wait(()=>!window.__smokeCapture,'capture '+name);}
 try{await wait(()=>document.querySelector('.main-menu'),'menu');document.querySelector('[aria-label="Continuar viagem"]').click();await wait(()=>document.querySelector('.scene-hotspot'),'scene');
 for(const size of ['1280x720','820x900','1920x1080']){window.__smokeResize=size;await wait(()=>!window.__smokeResize,'resize');await delay(300);const target=document.querySelector('.hotspot-npc');target.focus();await delay(300);assert(getComputedStyle(target).outlineStyle==='none','only short corners, no rectangular focus outline');const label=document.querySelector('.interaction-prompt').getBoundingClientRect(),scene=document.querySelector('.scene-image-wrap').getBoundingClientRect();assert(label.right<=scene.left+scene.width*.31,'left label avoids central aisle '+size);assert(label.left>=0,'label within window');await capture('qc-evidence-final-'+size);}
 document.querySelector('.scene-image').dispatchEvent(new PointerEvent('pointermove',{clientX:280,clientY:350,bubbles:true}));await delay(120);assert(document.querySelector('.game-cursor svg image').getAttribute('href').includes('preto'),'black cursor on white');assert(getComputedStyle(document.querySelector('.game-cursor')).width==='46px','large cursor');await capture('qc-cursor-final');window.__smokeReport='PASS: final evidence labels avoid the central aisle at 1280x720, 820x900, 1920x1080; target corners use opposite scene tone; original black cursor on white at 46px; latest source build rendered in native Windows.';window.__smokeStatus='PASS';
 }catch(e){window.__smokeStatus='FAIL '+e.message;}
})();
